- data/joincurioss.yml
Reducing text to make the size of the box match the others.
@direnakkoc - no rush on this - for when you get back! :)
> Update joincurioss.yml to make the Join CURIOSS box shorter

- content/news/new_grant_supports_development_of_curioss.md
The new  blog post should have a different name.
> Change title of the blog post

- content/about/_index.md
- content/about/contact.md
- content/about/join.md
- data/joincurioss.yml
There is no contact form linked. I also made the links a bit clearer, I think.
> docs: Change wording slightly

- content/about/_index.md
Final link in last sentence directed people to old 'join' page. Updated it to the 'contact' page.
> Corrected incorrect link on 'About' page

- content/about/_index.md
It was causing weird overlap issues on mobile.
> fix: remove classes from paragraph

- config.yaml
> feat: Add a Resources page

- .gitignore
Let me know if this still works for you.
> Removed some dead lines from .gitignore

- content/about/_index.md
I've updated the text about Sayeed and his contribution (as requested by Sayeed).
> Update 'Founding Organizers' content on the 'About CURIOSS' page

- content/about/members/_index.md
Added links to the Academic Map new UC Network members.
> Update links to Academic map

- content/about/members/_index.md
Added the link for SnT - University Luxembourg link to the Academic Map.
> Update members page with links to academic map

- content/resources/_index.md
> Add in a publications page

- config.yaml
Closes https://github.com/CURIOSSorg/curioss.org/issues/66
> Update cc license

- content/news/2025-02-27-academic-open-source-workshop-chaosscon.md
DRAFT PR for article on CHAOSScon workshop.
Waiting to upload image before requesting review.
> New article: academic-open-source-workshop-chaosscon.md

- content/news/2025-02-27-academic-open-source-workshop-chaosscon.md
1. Added Heading 3 and Section 3.1.
2. Made a minor edit to 1st para, 2nd sentence for ease of readability
> Add missing text to CHAOSScon report + minor edit

- data/homepage.yml
- layouts/index.html
closes: https://github.com/CURIOSSorg/curioss.org/issues/77
> update home page

- config.yaml
- content/about/join.md
closes: https://github.com/CURIOSSorg/curioss.org/issues/74
> Create join curioss page

- config.yaml
- layouts/partials/footer.html
Closes: https://github.com/CURIOSSorg/curioss.org/issues/86
> Update links from footer

- config.yaml
closes: https://github.com/CURIOSSorg/curioss.org/issues/91
> Add the Definition of an Academic OSPO to the Resources Dropdown list

- content/about/members/_index.md
closes: https://github.com/CURIOSSorg/curioss.org/issues/96
> Move the uni logo

- content/about/members/_index.md
> Fix error with UT Austin link on members page
